apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JJ8817/Hello-world-argo-app.git
    targetRevision: HEAD
    path: helm/hello-world
    helm:
      valueFiles:
        - values-staging.yaml
      parameters:
        - name: image.repository
          value: 97d8aecb895e00b0eb40f0100362d98556094528
        - name: image.tag
          value: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
